// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARQ2eAWRgPAr0RjdoCSQqU8ol2Pt71fjE',
    appId: '1:320776135501:web:0afaed6356f7f7c6c60d04',
    messagingSenderId: '320776135501',
    projectId: 'the-fire-45c47',
    authDomain: 'the-fire-45c47.firebaseapp.com',
    storageBucket: 'the-fire-45c47.appspot.com',
    measurementId: 'G-098GTKG4R3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEttPF2p_n4PKbXg3Meh0KckxoHlx478Y',
    appId: '1:320776135501:android:ecae25e0617ef0bfc60d04',
    messagingSenderId: '320776135501',
    projectId: 'the-fire-45c47',
    storageBucket: 'the-fire-45c47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDioTj65aFdNh_KGkH8YOXWzQpd-tZvz64',
    appId: '1:320776135501:ios:ac220407eb416755c60d04',
    messagingSenderId: '320776135501',
    projectId: 'the-fire-45c47',
    storageBucket: 'the-fire-45c47.appspot.com',
    iosBundleId: 'com.devcatstudio.theFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDioTj65aFdNh_KGkH8YOXWzQpd-tZvz64',
    appId: '1:320776135501:ios:ac220407eb416755c60d04',
    messagingSenderId: '320776135501',
    projectId: 'the-fire-45c47',
    storageBucket: 'the-fire-45c47.appspot.com',
    iosBundleId: 'com.devcatstudio.theFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARQ2eAWRgPAr0RjdoCSQqU8ol2Pt71fjE',
    appId: '1:320776135501:web:d60231729f9acd34c60d04',
    messagingSenderId: '320776135501',
    projectId: 'the-fire-45c47',
    authDomain: 'the-fire-45c47.firebaseapp.com',
    storageBucket: 'the-fire-45c47.appspot.com',
    measurementId: 'G-M5HQSX9BS3',
  );
}
