import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

class MenuIcons {
  static Map<String, dynamic> menuIcons = {
    'Dashboard': Icons.dashboard,
    'Attandance': Icons.fact_check_rounded,
    'Mark Attandance': Icons.fact_check_rounded,
    'Attendance View': Icons.calendar_today_rounded,
    'Order Delivery Status': FontAwesomeIcons.dolly,
    'Payslips': FontAwesomeIcons.moneyBill1Wave,
    'settings': Icons.settings,
    'Leave Status': FontAwesomeIcons.bed,
    'Task Manager': FontAwesomeIcons.boxesStacked,
    'Tasks Analysis': FontAwesomeIcons.chartBar,
    'Ticket Management System': FontAwesomeIcons.cubesStacked,
    'Ticker Setup': FontAwesomeIcons.gears,
    'Order': FontAwesomeIcons.utensils,
    'Balance Sheet': FontAwesomeIcons.sheetPlastic,
    'Income Statement': FontAwesomeIcons.fileLines,
    'Client Information': FontAwesomeIcons.circleInfo,
    'Customer Analysis': FontAwesomeIcons.personChalkboard,
    'Customer Retention': FontAwesomeIcons.personCircleCheck,
    'Branch': FontAwesomeIcons.locationPin,
    'Category': FontAwesomeIcons.shapes,
    'Client Wise': FontAwesomeIcons.slideshare,
    'Feedo Admin': FontAwesomeIcons.comment,
    'HR Analysis': FontAwesomeIcons.chartArea,
    'Issuance & Receiving Analysis': FontAwesomeIcons.arrowsLeftRightToLine,
    'Stock Status': FontAwesomeIcons.arrowTrendUp,
    'Product Cost Analysis': FontAwesomeIcons.fileContract,
    'Purchase Order List New': FontAwesomeIcons.clipboardList,
    'Purchase Reorder': FontAwesomeIcons.barsStaggered,
    'Purchase TP Analysis': FontAwesomeIcons.chartLine,
    'Purchase Tracking': FontAwesomeIcons.store,
    'Vendor Analysis New': FontAwesomeIcons.timeline,
    'Dine-In Queue': FontAwesomeIcons.usersLine,
    'Point of Sale (New)': FontAwesomeIcons.cashRegister,
    'Category Sales': FontAwesomeIcons.basketShopping,
    'Discount Analysis': FontAwesomeIcons.tag,
    'Drop Size': FontAwesomeIcons.droplet,
    'Hourly Sales': FontAwesomeIcons.hourglassHalf,
    'Order Process Tracking': FontAwesomeIcons.periscope,
    'Order Status': FontAwesomeIcons.cookieBite,
    'Order Status New': FontAwesomeIcons.cheese,
    'Payment Mode': FontAwesomeIcons.fileInvoiceDollar,
    'Purchases Vs Sales': FontAwesomeIcons.moneyCheck,
    'Sale Contribution Analysis': FontAwesomeIcons.circleDollarToSlot,
    'Sales View': FontAwesomeIcons.towerObservation,
    'Sales vs Expense': Icons.data_saver_off_outlined,
    'Dashboard Customization': FontAwesomeIcons.tableColumns,
    'Location Landmark': FontAwesomeIcons.earthAmericas,
    'Production Order List New': FontAwesomeIcons.productHunt,
    'Production Requisition': Icons.production_quantity_limits,
    'Financial Analysis': Icons.analytics_outlined,
    'Replication Monitor': FontAwesomeIcons.magnifyingGlass,
    'In Vs Out Transactions': FontAwesomeIcons.arrowsUpDown,
    'Item Consumption': FontAwesomeIcons.uncharted,
    'Recipe Analysis': FontAwesomeIcons.chartGantt,
    'Sales Return': FontAwesomeIcons.sackDollar,
    'Employee Advance/Loan': FontAwesomeIcons.handHoldingDollar,
    'Payroll': FontAwesomeIcons.fileInvoice,
  };
}
